### ISSUE TITLE
Quality doesn't scale

### ISSUE THREAD

**Issue by tritnaha** [JeppeTh/Cmore.bundle#1]
Seems like the plugin doesn't scale quality-wise, but rather get's stuck at ultra-low quality at all times.
 I assume this is not intentional?

**Comment by JeppeTh** [comment]
Well it's rather up to the client to choose quality. 
But sure I could add a configuration option to provide the different qualities to let you manually select one. 
Won't work in case HLS version 4 is used though.

**Comment by JeppeTh** [comment]
I added an option in 0bbb7b907386ef15a480723e69fd7e95b91b3ec4
