### ISSUE TITLE
Plugin not working with PMS 1.0?

### ISSUE THREAD

**Issue by tritnaha** [JeppeTh/Cmore.bundle#2]
Great patch for the quality-settings!

However, it seems like it's unable to play most streams now with a simple error-message saying the plex-server isn't responding, or that the stream is unavailable.

The verbose logging doesn't really give me anything to post for debugging. I can supply you with some if needed.

Running on Debian 8, PMS 1.0.0.2261

**Comment by JeppeTh** [comment]
See the forum post to show which logs to provide.
Don't remember if debug must be enabled in PMS or not. 

Or are you trying to play live steams that haven't yet started?

**Comment by JeppeTh** [comment]
Do you mean PMS 1.0 with 1.0 in heading?
I can't use later PMS versions since I'm currently stuck on windows xp... So I can't try that myself...

**Comment by tritnaha** [comment]
Latest PMS-build for Debian. Not playing any livestreams that have yet to start, that'd explain itself as to not working.

Version 2.7.0 / 1.0.0.2261 - latest available plexpass-release for Debian/Ubuntu.

I can arrange test-access to my machine if that'd help.

**Comment by JeppeTh** [comment]
Not sure I follow - what is your problem really?
Does ongoing live stream work or not?
Does channels work or not?

If any issue I need these logs:
.../Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.plugins.cmore.log
.../Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log
.../Plex Media Server/Logs/Plex Media Server.log

But first you probably need to:
enable "Plex Media Server debug logging"

**Comment by JeppeTh** [comment]
@tritnaha did you sort it out?

**Comment by tritnaha** [comment]
My apologies for the delay. I've yet to try it again as I've migrated my
setup back to Ubuntu again. I'll give the plugin a spin later today and
get back to you with logs if the issue is still existing, otherwise you
may close this issue.

Thanks!

Den 2016-07-13 kl. 23:42, skrev JeppeTh:

**Comment by JeppeTh** [comment]
Any news?

**Comment by tritnaha** [comment]
My bad. My machine's crashed so I have no means of testing this. Once i
get new hardware i'll test your plugin again to see if the issue
persists and if so open a new issue.

Sorry!

Den 2016-08-17 kl. 22:46, skrev JeppeTh:

**Comment by JeppeTh** [comment]
Ok, too bad.
